apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secret.sops.yaml
  - alert-manager
  - prom-stack
  - grafana
  - syslog
  - influxdb
  - snmp-exporter
  - loki
