---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: multus-mgmt
  namespace: system
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "multus-mgmt",
      "plugins": [
        {
          "type": "macvlan",
          "master": "br0",
          "mode": "bridge",
          "capabilities": {
            "ips": true
          },
          "ipam": {
            "type": "static",
            "routes": [
              { "dst": "10.0.20.0/24", "gw": "10.0.40.1" },
              { "dst": "10.0.40.0/24", "gw": "10.0.40.1" },
              { "dst": "10.0.50.0/24", "gw": "10.0.40.1" },
              { "dst": "10.0.60.0/24", "gw": "10.0.40.1" }
            ]
          }
        }
      ]
    }
